### ISSUE TITLE
composer install with root.

### ISSUE THREAD

**Issue by bigxu** [richarvey/nginx-php-fpm#169]
bash-4.3#  composer -v create-project craftcms/craft ./craftcms -s beta
Do not run Composer as root/super user! See https://getcomposer.org/root for details

how do you solve this problem ?

**Comment by richarvey** [comment]
I'll look into this and get an answer back to you asap.

**Comment by richarvey** [comment]
Hi, @bigxu I've pushed an image to docker with the tag 1.3.6-beta. Could you this and see if everything runs as expected?

I've added USER nginx to the container and tested that supervisorctl still works, however, could you use it to pull your code and see if composer installs now works, please.

**Comment by richarvey** [comment]
Will close in 3 days of no feedback

**Comment by bartholdbos** [comment]
@richarvey The [1.3.6-beta](https://github.com/richarvey/nginx-php-fpm/releases/tag/1.3.6-beta) tag seems to point to the same commit as [1.3.5](https://github.com/richarvey/nginx-php-fpm/releases/tag/1.3.5) The Composer warning about using root is still appearing when installing from Docker hub. When building the issue branch with docker myself I get the following errors:
```
Creating projects_app_1
Attaching to projects_app_1
app_1  | mkdir: can't create directory '/root/.ssh': Permission denied
app_1  | /start.sh: line 7: /root/.ssh/config: Permission denied
app_1  | /start.sh: line 8: /root/.ssh/config: Permission denied
app_1  | sed: can't create temp file '/etc/nginx/sites-available/default.confXXXXXX': Permission denied
app_1  | rm: can't remove '/var/www/html/index.php': Permission denied
app_1  | fatal: destination path '/var/www/html' already exists and is not an empty directory.
projects_app_1 exited with code 1
```
